version = 1

exclude_patterns = [
  "docs/**",
  "discord/ext/forms/__pycache__/**",
  "sphinx-source/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true
